// Chengeeker, 2026-10-04. GPL-2.0; see ../LICENSE. No network or client mutation.
const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const html = fs.readFileSync('admin/index.html', 'utf8');
const start = html.indexOf('function generateApplicationProxyConfig(');
assert(start > 0);
const elements = {};
for (const id of ['appProxyMappings', 'appProxyYaml', 'appProxyAddresses', 'appProxyDownloadBtn', 'appProxyStatus', 'appProxyGenerateBtn']) elements[id] = {value: '', textContent: '', events: {}, addEventListener(name, callback) { this.events[name] = callback; }};
let downloaded = '';
const context = {$: id => elements[id.slice(1)], downloadTextFile: (name, body) => { downloaded = body; }};
vm.createContext(context);
vm.runInContext(html.slice(start, html.indexOf('function bindEvents()', start)), context);
const generate = context.generateApplicationProxyConfig;
const name = 'JP 节点[80ms] = "测试" \\ 示例';
const result = generate('7893=' + name + '\n7894=US 节点');
assert.equal((result.yaml.match(/type: mixed/g) || []).length, 2);
assert.equal((result.yaml.match(/listen: 127\.0\.0\.1/g) || []).length, 2);
assert.equal((result.yaml.match(/udp: false/g) || []).length, 2);
assert.equal((result.yaml.match(/users: \[\]/g) || []).length, 2);
const proxyLines = result.yaml.split('\n').filter(line => line.trim().startsWith('proxy:'));
assert.equal(JSON.parse(proxyLines[0].trim().slice(7)), name);
assert(result.addresses.includes('http://127.0.0.1:7893'));
assert(result.addresses.includes('socks5://127.0.0.1:7894'));
assert(!result.yaml.includes('proxy-groups:'));
for (const input of ['', '7893', '0=JP', '1023=JP', '65536=JP', '1e4=JP', '7890=JP', '7891=JP', '9090=JP', '9443=JP', '7893=JP\n7893=US', '7893=', '7893=DIRECT', '7893=GLOBAL', '7893=https://example.com/sub', '7893=vless://example', '7893=JP\u0000']) assert.throws(() => generate(input));
assert(generate('1024=JP\n65535=US').yaml.includes('port: 65535'));
assert.throws(() => generate(Array.from({length: 17}, (_, i) => (10000 + i) + '=JP').join('\n')));
context.bindApplicationProxyEvents();
elements.appProxyMappings.value = '7893=JP'; elements.appProxyGenerateBtn.events.click();
assert(elements.appProxyYaml.value.includes('proxy: "JP"'));
elements.appProxyDownloadBtn.events.click(); assert.equal(downloaded, elements.appProxyYaml.value);
elements.appProxyMappings.events.input(); assert.equal(elements.appProxyYaml.value, ''); assert(elements.appProxyDownloadBtn.disabled);
elements.appProxyMappings.value = 'invalid'; elements.appProxyGenerateBtn.events.click(); assert.equal(elements.appProxyYaml.value, '');
console.log('PASS: dedicated listeners, quoted names, port validation, local-only/TCP-only, download and stale-output reset.');
